---
- name: Tworzy folder na Windows Serverze
  hosts: all
  gather_facts: no
  tasks:
    - name: Tworzenie folderu C:\TestFolder
      win_file:
        path: C:\TestFolder
        state: directory
