---
- name: Create folder on Windows Server machine
  hosts: all
  gather_facts: no
  tasks:
    - name: CreateFolder on C:\TestFolder
      win_file:
        path: C:\TestFolder
        state: directory
